spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: koc


---
spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      host: koc-mongo
      port: 27017
      authentication-database: admin
      database: koc

